packages:
  - apps/*

overrides:
  "brace-expansion@>=2.0.0 <2.1.4": 2.1.4
  "brace-expansion@>=4.0.0 <5.0.9": 5.0.9
  "dompurify@<=3.4.12": 3.4.13
  "js-yaml@>=4.0.0 <4.3.1": 4.3.1
  "nanoid@<3.3.18": 3.3.18
  postcss: 8.5.23
  "tar@<=7.5.20": 7.5.21

allowBuilds:
  "@swc/core": true
  argon2: true
  core-js: false
  esbuild: true
  fsevents: true
  msgpackr-extract: true
  unrs-resolver: true
