import { AuditLogSchema } from '#database/schema'

export type AuditAction =
  | 'user.role_changed'
  | 'user.deactivated'
  | 'user.reactivated'
  | 'project.created'
  | 'project.updated'
  | 'project.client_changed'
  | 'project.archived'
  | 'project.restored'
  | 'publication.created'
  | 'publication.updated'
  | 'publication.duplicated'
  | 'publication.status_changed'
  | 'publication.archived'
  | 'publication.restored'
  | 'publication.calendar_moved'
  | 'comment.created'
  | 'comment.updated'
  | 'comment.deleted'
  | 'comment.moderated'
  | 'publication.reviewed'
  | 'social.facebook_connected'
  | 'social.facebook_revoked'
  | 'social.facebook_scheduled'
  | 'social.facebook_retry_requested'
  | 'social.instagram_connected'
  | 'social.instagram_revoked'
  | 'social.instagram_scheduled'
  | 'social.instagram_retry_requested'
  | 'social.linkedin_connected'
  | 'social.linkedin_refreshed'
  | 'social.linkedin_revoked'
  | 'social.linkedin_scheduled'
  | 'social.linkedin_retry_requested'
  | 'social.pinterest_connected'
  | 'social.pinterest_refreshed'
  | 'social.pinterest_revoked'
  | 'social.pinterest_scheduled'
  | 'social.pinterest_retry_requested'
  | 'social.tiktok_connected'
  | 'social.tiktok_refreshed'
  | 'social.tiktok_revoked'
  | 'social.tiktok_scheduled'
  | 'social.tiktok_retry_requested'
  | 'media.upload_initialized'
  | 'media.upload_finalized'
  | 'media.attached'
  | 'media.updated'
  | 'media.reordered'
  | 'media.detached'
  | 'media.deleted'
  | 'media.purged'
  | 'ai.generation_created'
  | 'ai.variant_applied'
  | 'ai.generation_cancelled'
  | 'publication.network_variant_created'
  | 'publication.network_variant_generated'
  | 'publication.network_variant_updated'
  | 'publication.network_variant_approved'
  | 'publication.network_variant_stale'
  | 'annotation.created'
  | 'annotation.updated'
  | 'annotation.deleted'
  | 'annotation.moderated'
  | 'calendar.feed_created'
  | 'calendar.feed_revoked'
  | 'user.locale_changed'
  | 'publication.translation_generated'
  | 'publication.translation_updated'
  | 'publication.translation_approved'
  | 'system.job_retry_requested'

export default class AuditLog extends AuditLogSchema {
  declare action: AuditAction
  declare previousValues: Record<string, unknown>
  declare nextValues: Record<string, unknown>
}
