/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Backups: () => import('#controllers/admin/backups_controller'),
    Resources: () => import('#controllers/admin/resources_controller'),
    System: () => import('#controllers/admin/system_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  AiGenerations: () => import('#controllers/ai_generations_controller'),
  Annotations: () => import('#controllers/annotations_controller'),
  ApiDocs: () => import('#controllers/api_docs_controller'),
  auth: {
    Csrf: () => import('#controllers/auth/csrf_controller'),
    Me: () => import('#controllers/auth/me_controller'),
    Register: () => import('#controllers/auth/register_controller'),
    Session: () => import('#controllers/auth/session_controller'),
  },
  Calendar: () => import('#controllers/calendar_controller'),
  CalendarFeeds: () => import('#controllers/calendar_feeds_controller'),
  Comments: () => import('#controllers/comments_controller'),
  Discussion: () => import('#controllers/discussion_controller'),
  Facebook: () => import('#controllers/facebook_controller'),
  Health: () => import('#controllers/health_controller'),
  Instagram: () => import('#controllers/instagram_controller'),
  Linkedin: () => import('#controllers/linkedin_controller'),
  Locales: () => import('#controllers/locales_controller'),
  Media: () => import('#controllers/media_controller'),
  NetworkVariants: () => import('#controllers/network_variants_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  Pinterest: () => import('#controllers/pinterest_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Publications: () => import('#controllers/publications_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Statistics: () => import('#controllers/statistics_controller'),
  Supervision: () => import('#controllers/supervision_controller'),
  Tiktok: () => import('#controllers/tiktok_controller'),
  Translations: () => import('#controllers/translations_controller'),
  Users: () => import('#controllers/users_controller'),
}
