/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'health.live': {
    methods: ["GET","HEAD"],
    pattern: '/health/live',
    tokens: [{"old":"/health/live","type":0,"val":"health","end":""},{"old":"/health/live","type":0,"val":"live","end":""}],
    types: placeholder as Registry['health.live']['types'],
  },
  'health.ready': {
    methods: ["GET","HEAD"],
    pattern: '/health/ready',
    tokens: [{"old":"/health/ready","type":0,"val":"health","end":""},{"old":"/health/ready","type":0,"val":"ready","end":""}],
    types: placeholder as Registry['health.ready']['types'],
  },
  'docs.ui': {
    methods: ["GET","HEAD"],
    pattern: '/api/docs',
    tokens: [{"old":"/api/docs","type":0,"val":"api","end":""},{"old":"/api/docs","type":0,"val":"docs","end":""}],
    types: placeholder as Registry['docs.ui']['types'],
  },
  'docs.spec': {
    methods: ["GET","HEAD"],
    pattern: '/api/openapi.json',
    tokens: [{"old":"/api/openapi.json","type":0,"val":"api","end":""},{"old":"/api/openapi.json","type":0,"val":"openapi.json","end":""}],
    types: placeholder as Registry['docs.spec']['types'],
  },
  'auth.csrf': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/csrf',
    tokens: [{"old":"/api/v1/auth/csrf","type":0,"val":"api","end":""},{"old":"/api/v1/auth/csrf","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/csrf","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/csrf","type":0,"val":"csrf","end":""}],
    types: placeholder as Registry['auth.csrf']['types'],
  },
  'calendar.feed.public': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/calendar/feeds/:token',
    tokens: [{"old":"/api/v1/calendar/feeds/:token","type":0,"val":"api","end":""},{"old":"/api/v1/calendar/feeds/:token","type":0,"val":"v1","end":""},{"old":"/api/v1/calendar/feeds/:token","type":0,"val":"calendar","end":""},{"old":"/api/v1/calendar/feeds/:token","type":0,"val":"feeds","end":""},{"old":"/api/v1/calendar/feeds/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['calendar.feed.public']['types'],
  },
  'media.local_upload': {
    methods: ["PUT"],
    pattern: '/api/v1/media/local-upload',
    tokens: [{"old":"/api/v1/media/local-upload","type":0,"val":"api","end":""},{"old":"/api/v1/media/local-upload","type":0,"val":"v1","end":""},{"old":"/api/v1/media/local-upload","type":0,"val":"media","end":""},{"old":"/api/v1/media/local-upload","type":0,"val":"local-upload","end":""}],
    types: placeholder as Registry['media.local_upload']['types'],
  },
  'media.local_read': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/media/local-read',
    tokens: [{"old":"/api/v1/media/local-read","type":0,"val":"api","end":""},{"old":"/api/v1/media/local-read","type":0,"val":"v1","end":""},{"old":"/api/v1/media/local-read","type":0,"val":"media","end":""},{"old":"/api/v1/media/local-read","type":0,"val":"local-read","end":""}],
    types: placeholder as Registry['media.local_read']['types'],
  },
  'projects.clients': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/projects/clients',
    tokens: [{"old":"/api/v1/projects/clients","type":0,"val":"api","end":""},{"old":"/api/v1/projects/clients","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/clients","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['projects.clients']['types'],
  },
  'auth.register.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/register',
    tokens: [{"old":"/api/v1/auth/register","type":0,"val":"api","end":""},{"old":"/api/v1/auth/register","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/register","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register.store']['types'],
  },
  'auth.session.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.session.store']['types'],
  },
  'auth.me.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/me',
    tokens: [{"old":"/api/v1/auth/me","type":0,"val":"api","end":""},{"old":"/api/v1/auth/me","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/me","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me.show']['types'],
  },
  'auth.session.destroy': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.session.destroy']['types'],
  },
  'users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.show']['types'],
  },
  'users.locale': {
    methods: ["PATCH"],
    pattern: '/api/v1/users/me/locale',
    tokens: [{"old":"/api/v1/users/me/locale","type":0,"val":"api","end":""},{"old":"/api/v1/users/me/locale","type":0,"val":"v1","end":""},{"old":"/api/v1/users/me/locale","type":0,"val":"users","end":""},{"old":"/api/v1/users/me/locale","type":0,"val":"me","end":""},{"old":"/api/v1/users/me/locale","type":0,"val":"locale","end":""}],
    types: placeholder as Registry['users.locale']['types'],
  },
  'social.facebook.read.facebook.publication_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/facebook/publications/:id/status',
    tokens: [{"old":"/api/v1/social/facebook/publications/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/publications/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/publications/:id/status","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/publications/:id/status","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/publications/:id/status","type":0,"val":"publications","end":""},{"old":"/api/v1/social/facebook/publications/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/social/facebook/publications/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['social.facebook.read.facebook.publication_status']['types'],
  },
  'social.facebook.read.facebook.schedule_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/facebook/schedules/:id',
    tokens: [{"old":"/api/v1/social/facebook/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/schedules/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/schedules/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/schedules/:id","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/facebook/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.facebook.read.facebook.schedule_status']['types'],
  },
  'social.facebook.manage.facebook.oauth_start': {
    methods: ["POST"],
    pattern: '/api/v1/social/facebook/oauth/start',
    tokens: [{"old":"/api/v1/social/facebook/oauth/start","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/oauth/start","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/oauth/start","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/oauth/start","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/oauth/start","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/facebook/oauth/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['social.facebook.manage.facebook.oauth_start']['types'],
  },
  'social.facebook.manage.facebook.oauth_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/facebook/oauth/callback',
    tokens: [{"old":"/api/v1/social/facebook/oauth/callback","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/oauth/callback","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/oauth/callback","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/oauth/callback","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/oauth/callback","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/facebook/oauth/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['social.facebook.manage.facebook.oauth_callback']['types'],
  },
  'social.facebook.manage.facebook.accounts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/facebook/accounts',
    tokens: [{"old":"/api/v1/social/facebook/accounts","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/accounts","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/accounts","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['social.facebook.manage.facebook.accounts']['types'],
  },
  'social.facebook.manage.facebook.revoke': {
    methods: ["DELETE"],
    pattern: '/api/v1/social/facebook/accounts/:id',
    tokens: [{"old":"/api/v1/social/facebook/accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/accounts/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/accounts/:id","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/accounts/:id","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/facebook/accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.facebook.manage.facebook.revoke']['types'],
  },
  'social.facebook.manage.facebook.validate': {
    methods: ["POST"],
    pattern: '/api/v1/social/facebook/publications/:id/validate',
    tokens: [{"old":"/api/v1/social/facebook/publications/:id/validate","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/publications/:id/validate","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/publications/:id/validate","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/publications/:id/validate","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/publications/:id/validate","type":0,"val":"publications","end":""},{"old":"/api/v1/social/facebook/publications/:id/validate","type":1,"val":"id","end":""},{"old":"/api/v1/social/facebook/publications/:id/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['social.facebook.manage.facebook.validate']['types'],
  },
  'social.facebook.manage.facebook.schedule': {
    methods: ["POST"],
    pattern: '/api/v1/social/facebook/publications/:id/schedule',
    tokens: [{"old":"/api/v1/social/facebook/publications/:id/schedule","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/publications/:id/schedule","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/publications/:id/schedule","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/publications/:id/schedule","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/publications/:id/schedule","type":0,"val":"publications","end":""},{"old":"/api/v1/social/facebook/publications/:id/schedule","type":1,"val":"id","end":""},{"old":"/api/v1/social/facebook/publications/:id/schedule","type":0,"val":"schedule","end":""}],
    types: placeholder as Registry['social.facebook.manage.facebook.schedule']['types'],
  },
  'social.facebook.manage.facebook.retry': {
    methods: ["POST"],
    pattern: '/api/v1/social/facebook/schedules/:id/retry',
    tokens: [{"old":"/api/v1/social/facebook/schedules/:id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/social/facebook/schedules/:id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/social/facebook/schedules/:id/retry","type":0,"val":"social","end":""},{"old":"/api/v1/social/facebook/schedules/:id/retry","type":0,"val":"facebook","end":""},{"old":"/api/v1/social/facebook/schedules/:id/retry","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/facebook/schedules/:id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/social/facebook/schedules/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['social.facebook.manage.facebook.retry']['types'],
  },
  'social.pinterest.read.pinterest.publication_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/pinterest/publications/:id/status',
    tokens: [{"old":"/api/v1/social/pinterest/publications/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/publications/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/publications/:id/status","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/publications/:id/status","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/publications/:id/status","type":0,"val":"publications","end":""},{"old":"/api/v1/social/pinterest/publications/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/social/pinterest/publications/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['social.pinterest.read.pinterest.publication_status']['types'],
  },
  'social.pinterest.read.pinterest.schedule_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/pinterest/schedules/:id',
    tokens: [{"old":"/api/v1/social/pinterest/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/schedules/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/schedules/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/schedules/:id","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/pinterest/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.pinterest.read.pinterest.schedule_status']['types'],
  },
  'social.pinterest.manage.pinterest.oauth_start': {
    methods: ["POST"],
    pattern: '/api/v1/social/pinterest/oauth/start',
    tokens: [{"old":"/api/v1/social/pinterest/oauth/start","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/oauth/start","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/oauth/start","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/oauth/start","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/oauth/start","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/pinterest/oauth/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.oauth_start']['types'],
  },
  'social.pinterest.manage.pinterest.oauth_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/pinterest/oauth/callback',
    tokens: [{"old":"/api/v1/social/pinterest/oauth/callback","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/oauth/callback","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/oauth/callback","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/oauth/callback","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/oauth/callback","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/pinterest/oauth/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.oauth_callback']['types'],
  },
  'social.pinterest.manage.pinterest.accounts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/pinterest/accounts',
    tokens: [{"old":"/api/v1/social/pinterest/accounts","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/accounts","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/accounts","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.accounts']['types'],
  },
  'social.pinterest.manage.pinterest.refresh': {
    methods: ["POST"],
    pattern: '/api/v1/social/pinterest/accounts/:id/refresh',
    tokens: [{"old":"/api/v1/social/pinterest/accounts/:id/refresh","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/accounts/:id/refresh","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/accounts/:id/refresh","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/accounts/:id/refresh","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/accounts/:id/refresh","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/pinterest/accounts/:id/refresh","type":1,"val":"id","end":""},{"old":"/api/v1/social/pinterest/accounts/:id/refresh","type":0,"val":"refresh","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.refresh']['types'],
  },
  'social.pinterest.manage.pinterest.revoke': {
    methods: ["DELETE"],
    pattern: '/api/v1/social/pinterest/accounts/:id',
    tokens: [{"old":"/api/v1/social/pinterest/accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/accounts/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/accounts/:id","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/accounts/:id","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/pinterest/accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.revoke']['types'],
  },
  'social.pinterest.manage.pinterest.validate': {
    methods: ["POST"],
    pattern: '/api/v1/social/pinterest/publications/:id/validate',
    tokens: [{"old":"/api/v1/social/pinterest/publications/:id/validate","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/publications/:id/validate","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/publications/:id/validate","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/publications/:id/validate","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/publications/:id/validate","type":0,"val":"publications","end":""},{"old":"/api/v1/social/pinterest/publications/:id/validate","type":1,"val":"id","end":""},{"old":"/api/v1/social/pinterest/publications/:id/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.validate']['types'],
  },
  'social.pinterest.manage.pinterest.schedule': {
    methods: ["POST"],
    pattern: '/api/v1/social/pinterest/publications/:id/schedule',
    tokens: [{"old":"/api/v1/social/pinterest/publications/:id/schedule","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/publications/:id/schedule","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/publications/:id/schedule","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/publications/:id/schedule","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/publications/:id/schedule","type":0,"val":"publications","end":""},{"old":"/api/v1/social/pinterest/publications/:id/schedule","type":1,"val":"id","end":""},{"old":"/api/v1/social/pinterest/publications/:id/schedule","type":0,"val":"schedule","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.schedule']['types'],
  },
  'social.pinterest.manage.pinterest.retry': {
    methods: ["POST"],
    pattern: '/api/v1/social/pinterest/schedules/:id/retry',
    tokens: [{"old":"/api/v1/social/pinterest/schedules/:id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/social/pinterest/schedules/:id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/social/pinterest/schedules/:id/retry","type":0,"val":"social","end":""},{"old":"/api/v1/social/pinterest/schedules/:id/retry","type":0,"val":"pinterest","end":""},{"old":"/api/v1/social/pinterest/schedules/:id/retry","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/pinterest/schedules/:id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/social/pinterest/schedules/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['social.pinterest.manage.pinterest.retry']['types'],
  },
  'social.tiktok.read.tik_tok.publication_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/tiktok/publications/:id/status',
    tokens: [{"old":"/api/v1/social/tiktok/publications/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/publications/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/publications/:id/status","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/publications/:id/status","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/publications/:id/status","type":0,"val":"publications","end":""},{"old":"/api/v1/social/tiktok/publications/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/social/tiktok/publications/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['social.tiktok.read.tik_tok.publication_status']['types'],
  },
  'social.tiktok.read.tik_tok.schedule_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/tiktok/schedules/:id',
    tokens: [{"old":"/api/v1/social/tiktok/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/schedules/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/schedules/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/schedules/:id","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/tiktok/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.tiktok.read.tik_tok.schedule_status']['types'],
  },
  'social.tiktok.manage.tik_tok.oauth_start': {
    methods: ["POST"],
    pattern: '/api/v1/social/tiktok/oauth/start',
    tokens: [{"old":"/api/v1/social/tiktok/oauth/start","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/oauth/start","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/oauth/start","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/oauth/start","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/oauth/start","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/tiktok/oauth/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.oauth_start']['types'],
  },
  'social.tiktok.manage.tik_tok.oauth_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/tiktok/oauth/callback',
    tokens: [{"old":"/api/v1/social/tiktok/oauth/callback","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/oauth/callback","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/oauth/callback","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/oauth/callback","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/oauth/callback","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/tiktok/oauth/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.oauth_callback']['types'],
  },
  'social.tiktok.manage.tik_tok.accounts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/tiktok/accounts',
    tokens: [{"old":"/api/v1/social/tiktok/accounts","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/accounts","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/accounts","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.accounts']['types'],
  },
  'social.tiktok.manage.tik_tok.refresh': {
    methods: ["POST"],
    pattern: '/api/v1/social/tiktok/accounts/:id/refresh',
    tokens: [{"old":"/api/v1/social/tiktok/accounts/:id/refresh","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/accounts/:id/refresh","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/accounts/:id/refresh","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/accounts/:id/refresh","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/accounts/:id/refresh","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/tiktok/accounts/:id/refresh","type":1,"val":"id","end":""},{"old":"/api/v1/social/tiktok/accounts/:id/refresh","type":0,"val":"refresh","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.refresh']['types'],
  },
  'social.tiktok.manage.tik_tok.revoke': {
    methods: ["DELETE"],
    pattern: '/api/v1/social/tiktok/accounts/:id',
    tokens: [{"old":"/api/v1/social/tiktok/accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/accounts/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/accounts/:id","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/accounts/:id","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/tiktok/accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.revoke']['types'],
  },
  'social.tiktok.manage.tik_tok.validate': {
    methods: ["POST"],
    pattern: '/api/v1/social/tiktok/publications/:id/validate',
    tokens: [{"old":"/api/v1/social/tiktok/publications/:id/validate","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/publications/:id/validate","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/publications/:id/validate","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/publications/:id/validate","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/publications/:id/validate","type":0,"val":"publications","end":""},{"old":"/api/v1/social/tiktok/publications/:id/validate","type":1,"val":"id","end":""},{"old":"/api/v1/social/tiktok/publications/:id/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.validate']['types'],
  },
  'social.tiktok.manage.tik_tok.schedule': {
    methods: ["POST"],
    pattern: '/api/v1/social/tiktok/publications/:id/schedule',
    tokens: [{"old":"/api/v1/social/tiktok/publications/:id/schedule","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/publications/:id/schedule","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/publications/:id/schedule","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/publications/:id/schedule","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/publications/:id/schedule","type":0,"val":"publications","end":""},{"old":"/api/v1/social/tiktok/publications/:id/schedule","type":1,"val":"id","end":""},{"old":"/api/v1/social/tiktok/publications/:id/schedule","type":0,"val":"schedule","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.schedule']['types'],
  },
  'social.tiktok.manage.tik_tok.retry': {
    methods: ["POST"],
    pattern: '/api/v1/social/tiktok/schedules/:id/retry',
    tokens: [{"old":"/api/v1/social/tiktok/schedules/:id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/social/tiktok/schedules/:id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/social/tiktok/schedules/:id/retry","type":0,"val":"social","end":""},{"old":"/api/v1/social/tiktok/schedules/:id/retry","type":0,"val":"tiktok","end":""},{"old":"/api/v1/social/tiktok/schedules/:id/retry","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/tiktok/schedules/:id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/social/tiktok/schedules/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['social.tiktok.manage.tik_tok.retry']['types'],
  },
  'social.linkedin.read.linked_in.publication_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/linkedin/publications/:id/status',
    tokens: [{"old":"/api/v1/social/linkedin/publications/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/publications/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/publications/:id/status","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/publications/:id/status","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/publications/:id/status","type":0,"val":"publications","end":""},{"old":"/api/v1/social/linkedin/publications/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/social/linkedin/publications/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['social.linkedin.read.linked_in.publication_status']['types'],
  },
  'social.linkedin.read.linked_in.schedule_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/linkedin/schedules/:id',
    tokens: [{"old":"/api/v1/social/linkedin/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/schedules/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/schedules/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/schedules/:id","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/linkedin/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.linkedin.read.linked_in.schedule_status']['types'],
  },
  'social.linkedin.manage.linked_in.oauth_start': {
    methods: ["POST"],
    pattern: '/api/v1/social/linkedin/oauth/start',
    tokens: [{"old":"/api/v1/social/linkedin/oauth/start","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/oauth/start","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/oauth/start","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/oauth/start","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/oauth/start","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/linkedin/oauth/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.oauth_start']['types'],
  },
  'social.linkedin.manage.linked_in.oauth_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/linkedin/oauth/callback',
    tokens: [{"old":"/api/v1/social/linkedin/oauth/callback","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/oauth/callback","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/oauth/callback","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/oauth/callback","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/oauth/callback","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/linkedin/oauth/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.oauth_callback']['types'],
  },
  'social.linkedin.manage.linked_in.accounts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/linkedin/accounts',
    tokens: [{"old":"/api/v1/social/linkedin/accounts","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/accounts","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/accounts","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.accounts']['types'],
  },
  'social.linkedin.manage.linked_in.refresh': {
    methods: ["POST"],
    pattern: '/api/v1/social/linkedin/accounts/:id/refresh',
    tokens: [{"old":"/api/v1/social/linkedin/accounts/:id/refresh","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/accounts/:id/refresh","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/accounts/:id/refresh","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/accounts/:id/refresh","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/accounts/:id/refresh","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/linkedin/accounts/:id/refresh","type":1,"val":"id","end":""},{"old":"/api/v1/social/linkedin/accounts/:id/refresh","type":0,"val":"refresh","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.refresh']['types'],
  },
  'social.linkedin.manage.linked_in.revoke': {
    methods: ["DELETE"],
    pattern: '/api/v1/social/linkedin/accounts/:id',
    tokens: [{"old":"/api/v1/social/linkedin/accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/accounts/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/accounts/:id","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/accounts/:id","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/linkedin/accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.revoke']['types'],
  },
  'social.linkedin.manage.linked_in.validate': {
    methods: ["POST"],
    pattern: '/api/v1/social/linkedin/publications/:id/validate',
    tokens: [{"old":"/api/v1/social/linkedin/publications/:id/validate","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/publications/:id/validate","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/publications/:id/validate","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/publications/:id/validate","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/publications/:id/validate","type":0,"val":"publications","end":""},{"old":"/api/v1/social/linkedin/publications/:id/validate","type":1,"val":"id","end":""},{"old":"/api/v1/social/linkedin/publications/:id/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.validate']['types'],
  },
  'social.linkedin.manage.linked_in.schedule': {
    methods: ["POST"],
    pattern: '/api/v1/social/linkedin/publications/:id/schedule',
    tokens: [{"old":"/api/v1/social/linkedin/publications/:id/schedule","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/publications/:id/schedule","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/publications/:id/schedule","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/publications/:id/schedule","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/publications/:id/schedule","type":0,"val":"publications","end":""},{"old":"/api/v1/social/linkedin/publications/:id/schedule","type":1,"val":"id","end":""},{"old":"/api/v1/social/linkedin/publications/:id/schedule","type":0,"val":"schedule","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.schedule']['types'],
  },
  'social.linkedin.manage.linked_in.retry': {
    methods: ["POST"],
    pattern: '/api/v1/social/linkedin/schedules/:id/retry',
    tokens: [{"old":"/api/v1/social/linkedin/schedules/:id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/social/linkedin/schedules/:id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/social/linkedin/schedules/:id/retry","type":0,"val":"social","end":""},{"old":"/api/v1/social/linkedin/schedules/:id/retry","type":0,"val":"linkedin","end":""},{"old":"/api/v1/social/linkedin/schedules/:id/retry","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/linkedin/schedules/:id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/social/linkedin/schedules/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['social.linkedin.manage.linked_in.retry']['types'],
  },
  'social.instagram.read.instagram.publication_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/instagram/publications/:id/status',
    tokens: [{"old":"/api/v1/social/instagram/publications/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/publications/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/publications/:id/status","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/publications/:id/status","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/publications/:id/status","type":0,"val":"publications","end":""},{"old":"/api/v1/social/instagram/publications/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/social/instagram/publications/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['social.instagram.read.instagram.publication_status']['types'],
  },
  'social.instagram.read.instagram.schedule_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/instagram/schedules/:id',
    tokens: [{"old":"/api/v1/social/instagram/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/schedules/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/schedules/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/schedules/:id","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/instagram/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.instagram.read.instagram.schedule_status']['types'],
  },
  'social.instagram.manage.instagram.oauth_start': {
    methods: ["POST"],
    pattern: '/api/v1/social/instagram/oauth/start',
    tokens: [{"old":"/api/v1/social/instagram/oauth/start","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/oauth/start","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/oauth/start","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/oauth/start","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/oauth/start","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/instagram/oauth/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['social.instagram.manage.instagram.oauth_start']['types'],
  },
  'social.instagram.manage.instagram.oauth_callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/instagram/oauth/callback',
    tokens: [{"old":"/api/v1/social/instagram/oauth/callback","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/oauth/callback","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/oauth/callback","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/oauth/callback","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/oauth/callback","type":0,"val":"oauth","end":""},{"old":"/api/v1/social/instagram/oauth/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['social.instagram.manage.instagram.oauth_callback']['types'],
  },
  'social.instagram.manage.instagram.accounts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/social/instagram/accounts',
    tokens: [{"old":"/api/v1/social/instagram/accounts","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/accounts","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/accounts","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['social.instagram.manage.instagram.accounts']['types'],
  },
  'social.instagram.manage.instagram.revoke': {
    methods: ["DELETE"],
    pattern: '/api/v1/social/instagram/accounts/:id',
    tokens: [{"old":"/api/v1/social/instagram/accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/accounts/:id","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/accounts/:id","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/accounts/:id","type":0,"val":"accounts","end":""},{"old":"/api/v1/social/instagram/accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.instagram.manage.instagram.revoke']['types'],
  },
  'social.instagram.manage.instagram.validate': {
    methods: ["POST"],
    pattern: '/api/v1/social/instagram/publications/:id/validate',
    tokens: [{"old":"/api/v1/social/instagram/publications/:id/validate","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/publications/:id/validate","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/publications/:id/validate","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/publications/:id/validate","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/publications/:id/validate","type":0,"val":"publications","end":""},{"old":"/api/v1/social/instagram/publications/:id/validate","type":1,"val":"id","end":""},{"old":"/api/v1/social/instagram/publications/:id/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['social.instagram.manage.instagram.validate']['types'],
  },
  'social.instagram.manage.instagram.schedule': {
    methods: ["POST"],
    pattern: '/api/v1/social/instagram/publications/:id/schedule',
    tokens: [{"old":"/api/v1/social/instagram/publications/:id/schedule","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/publications/:id/schedule","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/publications/:id/schedule","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/publications/:id/schedule","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/publications/:id/schedule","type":0,"val":"publications","end":""},{"old":"/api/v1/social/instagram/publications/:id/schedule","type":1,"val":"id","end":""},{"old":"/api/v1/social/instagram/publications/:id/schedule","type":0,"val":"schedule","end":""}],
    types: placeholder as Registry['social.instagram.manage.instagram.schedule']['types'],
  },
  'social.instagram.manage.instagram.retry': {
    methods: ["POST"],
    pattern: '/api/v1/social/instagram/schedules/:id/retry',
    tokens: [{"old":"/api/v1/social/instagram/schedules/:id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/social/instagram/schedules/:id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/social/instagram/schedules/:id/retry","type":0,"val":"social","end":""},{"old":"/api/v1/social/instagram/schedules/:id/retry","type":0,"val":"instagram","end":""},{"old":"/api/v1/social/instagram/schedules/:id/retry","type":0,"val":"schedules","end":""},{"old":"/api/v1/social/instagram/schedules/:id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/social/instagram/schedules/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['social.instagram.manage.instagram.retry']['types'],
  },
  'admin.admin_resources.overview': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/overview',
    tokens: [{"old":"/api/v1/admin/overview","type":0,"val":"api","end":""},{"old":"/api/v1/admin/overview","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/overview","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/overview","type":0,"val":"overview","end":""}],
    types: placeholder as Registry['admin.admin_resources.overview']['types'],
  },
  'admin.admin_users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/users',
    tokens: [{"old":"/api/v1/admin/users","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.admin_users.index']['types'],
  },
  'admin.admin_users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/users/:id',
    tokens: [{"old":"/api/v1/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.admin_users.show']['types'],
  },
  'admin.admin_users.update_role': {
    methods: ["PATCH"],
    pattern: '/api/v1/admin/users/:id/role',
    tokens: [{"old":"/api/v1/admin/users/:id/role","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id/role","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id/role","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id/role","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id/role","type":1,"val":"id","end":""},{"old":"/api/v1/admin/users/:id/role","type":0,"val":"role","end":""}],
    types: placeholder as Registry['admin.admin_users.update_role']['types'],
  },
  'admin.admin_users.update_status': {
    methods: ["PATCH"],
    pattern: '/api/v1/admin/users/:id/status',
    tokens: [{"old":"/api/v1/admin/users/:id/status","type":0,"val":"api","end":""},{"old":"/api/v1/admin/users/:id/status","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/users/:id/status","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/users/:id/status","type":0,"val":"users","end":""},{"old":"/api/v1/admin/users/:id/status","type":1,"val":"id","end":""},{"old":"/api/v1/admin/users/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin.admin_users.update_status']['types'],
  },
  'admin.admin_resources.projects': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/projects',
    tokens: [{"old":"/api/v1/admin/projects","type":0,"val":"api","end":""},{"old":"/api/v1/admin/projects","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/projects","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['admin.admin_resources.projects']['types'],
  },
  'admin.admin_resources.project': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/projects/:id',
    tokens: [{"old":"/api/v1/admin/projects/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/projects/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/projects/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/v1/admin/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.admin_resources.project']['types'],
  },
  'admin.admin_resources.archive_project': {
    methods: ["POST"],
    pattern: '/api/v1/admin/projects/:id/archive',
    tokens: [{"old":"/api/v1/admin/projects/:id/archive","type":0,"val":"api","end":""},{"old":"/api/v1/admin/projects/:id/archive","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/projects/:id/archive","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/projects/:id/archive","type":0,"val":"projects","end":""},{"old":"/api/v1/admin/projects/:id/archive","type":1,"val":"id","end":""},{"old":"/api/v1/admin/projects/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['admin.admin_resources.archive_project']['types'],
  },
  'admin.admin_resources.restore_project': {
    methods: ["POST"],
    pattern: '/api/v1/admin/projects/:id/restore',
    tokens: [{"old":"/api/v1/admin/projects/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/admin/projects/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/projects/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/projects/:id/restore","type":0,"val":"projects","end":""},{"old":"/api/v1/admin/projects/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/admin/projects/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['admin.admin_resources.restore_project']['types'],
  },
  'admin.admin_resources.publications': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/publications',
    tokens: [{"old":"/api/v1/admin/publications","type":0,"val":"api","end":""},{"old":"/api/v1/admin/publications","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/publications","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/publications","type":0,"val":"publications","end":""}],
    types: placeholder as Registry['admin.admin_resources.publications']['types'],
  },
  'admin.admin_resources.publication': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/publications/:id',
    tokens: [{"old":"/api/v1/admin/publications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/publications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/publications/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/publications/:id","type":0,"val":"publications","end":""},{"old":"/api/v1/admin/publications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.admin_resources.publication']['types'],
  },
  'admin.admin_resources.archive_publication': {
    methods: ["POST"],
    pattern: '/api/v1/admin/publications/:id/archive',
    tokens: [{"old":"/api/v1/admin/publications/:id/archive","type":0,"val":"api","end":""},{"old":"/api/v1/admin/publications/:id/archive","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/publications/:id/archive","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/publications/:id/archive","type":0,"val":"publications","end":""},{"old":"/api/v1/admin/publications/:id/archive","type":1,"val":"id","end":""},{"old":"/api/v1/admin/publications/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['admin.admin_resources.archive_publication']['types'],
  },
  'admin.admin_resources.restore_publication': {
    methods: ["POST"],
    pattern: '/api/v1/admin/publications/:id/restore',
    tokens: [{"old":"/api/v1/admin/publications/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/admin/publications/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/publications/:id/restore","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/publications/:id/restore","type":0,"val":"publications","end":""},{"old":"/api/v1/admin/publications/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/admin/publications/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['admin.admin_resources.restore_publication']['types'],
  },
  'admin.admin_resources.social_accounts': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/social-accounts',
    tokens: [{"old":"/api/v1/admin/social-accounts","type":0,"val":"api","end":""},{"old":"/api/v1/admin/social-accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/social-accounts","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/social-accounts","type":0,"val":"social-accounts","end":""}],
    types: placeholder as Registry['admin.admin_resources.social_accounts']['types'],
  },
  'admin.admin_resources.social_account': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/social-accounts/:id',
    tokens: [{"old":"/api/v1/admin/social-accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/social-accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/social-accounts/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/social-accounts/:id","type":0,"val":"social-accounts","end":""},{"old":"/api/v1/admin/social-accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.admin_resources.social_account']['types'],
  },
  'admin.admin_resources.incidents': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/incidents',
    tokens: [{"old":"/api/v1/admin/incidents","type":0,"val":"api","end":""},{"old":"/api/v1/admin/incidents","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/incidents","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/incidents","type":0,"val":"incidents","end":""}],
    types: placeholder as Registry['admin.admin_resources.incidents']['types'],
  },
  'admin.admin_resources.incident': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/incidents/:id',
    tokens: [{"old":"/api/v1/admin/incidents/:id","type":0,"val":"api","end":""},{"old":"/api/v1/admin/incidents/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/incidents/:id","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/incidents/:id","type":0,"val":"incidents","end":""},{"old":"/api/v1/admin/incidents/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.admin_resources.incident']['types'],
  },
  'admin.admin_resources.audit_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/audit-logs',
    tokens: [{"old":"/api/v1/admin/audit-logs","type":0,"val":"api","end":""},{"old":"/api/v1/admin/audit-logs","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/audit-logs","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/audit-logs","type":0,"val":"audit-logs","end":""}],
    types: placeholder as Registry['admin.admin_resources.audit_logs']['types'],
  },
  'admin.admin_system.status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/system/status',
    tokens: [{"old":"/api/v1/admin/system/status","type":0,"val":"api","end":""},{"old":"/api/v1/admin/system/status","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/system/status","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/system/status","type":0,"val":"system","end":""},{"old":"/api/v1/admin/system/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['admin.admin_system.status']['types'],
  },
  'admin.admin_system.metrics': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/system/metrics',
    tokens: [{"old":"/api/v1/admin/system/metrics","type":0,"val":"api","end":""},{"old":"/api/v1/admin/system/metrics","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/system/metrics","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/system/metrics","type":0,"val":"system","end":""},{"old":"/api/v1/admin/system/metrics","type":0,"val":"metrics","end":""}],
    types: placeholder as Registry['admin.admin_system.metrics']['types'],
  },
  'admin.admin_backups.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin/backups',
    tokens: [{"old":"/api/v1/admin/backups","type":0,"val":"api","end":""},{"old":"/api/v1/admin/backups","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/backups","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/backups","type":0,"val":"backups","end":""}],
    types: placeholder as Registry['admin.admin_backups.index']['types'],
  },
  'admin.admin_system.retry': {
    methods: ["POST"],
    pattern: '/api/v1/admin/system/jobs/:jobId/retry',
    tokens: [{"old":"/api/v1/admin/system/jobs/:jobId/retry","type":0,"val":"api","end":""},{"old":"/api/v1/admin/system/jobs/:jobId/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/admin/system/jobs/:jobId/retry","type":0,"val":"admin","end":""},{"old":"/api/v1/admin/system/jobs/:jobId/retry","type":0,"val":"system","end":""},{"old":"/api/v1/admin/system/jobs/:jobId/retry","type":0,"val":"jobs","end":""},{"old":"/api/v1/admin/system/jobs/:jobId/retry","type":1,"val":"jobId","end":""},{"old":"/api/v1/admin/system/jobs/:jobId/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['admin.admin_system.retry']['types'],
  },
  'supervision.supervision.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/supervision/summary',
    tokens: [{"old":"/api/v1/supervision/summary","type":0,"val":"api","end":""},{"old":"/api/v1/supervision/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/supervision/summary","type":0,"val":"supervision","end":""},{"old":"/api/v1/supervision/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['supervision.supervision.summary']['types'],
  },
  'supervision.supervision.items': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/supervision/items',
    tokens: [{"old":"/api/v1/supervision/items","type":0,"val":"api","end":""},{"old":"/api/v1/supervision/items","type":0,"val":"v1","end":""},{"old":"/api/v1/supervision/items","type":0,"val":"supervision","end":""},{"old":"/api/v1/supervision/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['supervision.supervision.items']['types'],
  },
  'supervision.supervision.mark_read': {
    methods: ["PATCH"],
    pattern: '/api/v1/supervision/notifications/:id/read',
    tokens: [{"old":"/api/v1/supervision/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/v1/supervision/notifications/:id/read","type":0,"val":"v1","end":""},{"old":"/api/v1/supervision/notifications/:id/read","type":0,"val":"supervision","end":""},{"old":"/api/v1/supervision/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/v1/supervision/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/v1/supervision/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['supervision.supervision.mark_read']['types'],
  },
  'statistics.statistics.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/statistics',
    tokens: [{"old":"/api/v1/statistics","type":0,"val":"api","end":""},{"old":"/api/v1/statistics","type":0,"val":"v1","end":""},{"old":"/api/v1/statistics","type":0,"val":"statistics","end":""}],
    types: placeholder as Registry['statistics.statistics.show']['types'],
  },
  'statistics.statistics.export': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/statistics/export.csv',
    tokens: [{"old":"/api/v1/statistics/export.csv","type":0,"val":"api","end":""},{"old":"/api/v1/statistics/export.csv","type":0,"val":"v1","end":""},{"old":"/api/v1/statistics/export.csv","type":0,"val":"statistics","end":""},{"old":"/api/v1/statistics/export.csv","type":0,"val":"export.csv","end":""}],
    types: placeholder as Registry['statistics.statistics.export']['types'],
  },
  'calendar.export.calendar_feeds.export': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/calendar/export.ics',
    tokens: [{"old":"/api/v1/calendar/export.ics","type":0,"val":"api","end":""},{"old":"/api/v1/calendar/export.ics","type":0,"val":"v1","end":""},{"old":"/api/v1/calendar/export.ics","type":0,"val":"calendar","end":""},{"old":"/api/v1/calendar/export.ics","type":0,"val":"export.ics","end":""}],
    types: placeholder as Registry['calendar.export.calendar_feeds.export']['types'],
  },
  'calendar.export.calendar_feeds.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/calendar/feeds',
    tokens: [{"old":"/api/v1/calendar/feeds","type":0,"val":"api","end":""},{"old":"/api/v1/calendar/feeds","type":0,"val":"v1","end":""},{"old":"/api/v1/calendar/feeds","type":0,"val":"calendar","end":""},{"old":"/api/v1/calendar/feeds","type":0,"val":"feeds","end":""}],
    types: placeholder as Registry['calendar.export.calendar_feeds.index']['types'],
  },
  'calendar.export.calendar_feeds.store': {
    methods: ["POST"],
    pattern: '/api/v1/calendar/feeds',
    tokens: [{"old":"/api/v1/calendar/feeds","type":0,"val":"api","end":""},{"old":"/api/v1/calendar/feeds","type":0,"val":"v1","end":""},{"old":"/api/v1/calendar/feeds","type":0,"val":"calendar","end":""},{"old":"/api/v1/calendar/feeds","type":0,"val":"feeds","end":""}],
    types: placeholder as Registry['calendar.export.calendar_feeds.store']['types'],
  },
  'calendar.export.calendar_feeds.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/calendar/feeds/:id',
    tokens: [{"old":"/api/v1/calendar/feeds/:id","type":0,"val":"api","end":""},{"old":"/api/v1/calendar/feeds/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/calendar/feeds/:id","type":0,"val":"calendar","end":""},{"old":"/api/v1/calendar/feeds/:id","type":0,"val":"feeds","end":""},{"old":"/api/v1/calendar/feeds/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['calendar.export.calendar_feeds.destroy']['types'],
  },
  'ai-generations.ai_generations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:id/ai-generations',
    tokens: [{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"ai-generations","end":""}],
    types: placeholder as Registry['ai-generations.ai_generations.index']['types'],
  },
  'ai-generations.ai_generations.store': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/ai-generations',
    tokens: [{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/ai-generations","type":0,"val":"ai-generations","end":""}],
    types: placeholder as Registry['ai-generations.ai_generations.store']['types'],
  },
  'ai-generations.ai_generations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/ai-generations/:id',
    tokens: [{"old":"/api/v1/ai-generations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/ai-generations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/ai-generations/:id","type":0,"val":"ai-generations","end":""},{"old":"/api/v1/ai-generations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['ai-generations.ai_generations.show']['types'],
  },
  'ai-generations.ai_generations.apply': {
    methods: ["POST"],
    pattern: '/api/v1/ai-generations/:id/apply',
    tokens: [{"old":"/api/v1/ai-generations/:id/apply","type":0,"val":"api","end":""},{"old":"/api/v1/ai-generations/:id/apply","type":0,"val":"v1","end":""},{"old":"/api/v1/ai-generations/:id/apply","type":0,"val":"ai-generations","end":""},{"old":"/api/v1/ai-generations/:id/apply","type":1,"val":"id","end":""},{"old":"/api/v1/ai-generations/:id/apply","type":0,"val":"apply","end":""}],
    types: placeholder as Registry['ai-generations.ai_generations.apply']['types'],
  },
  'ai-generations.ai_generations.cancel': {
    methods: ["POST"],
    pattern: '/api/v1/ai-generations/:id/cancel',
    tokens: [{"old":"/api/v1/ai-generations/:id/cancel","type":0,"val":"api","end":""},{"old":"/api/v1/ai-generations/:id/cancel","type":0,"val":"v1","end":""},{"old":"/api/v1/ai-generations/:id/cancel","type":0,"val":"ai-generations","end":""},{"old":"/api/v1/ai-generations/:id/cancel","type":1,"val":"id","end":""},{"old":"/api/v1/ai-generations/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['ai-generations.ai_generations.cancel']['types'],
  },
  'network-variants.read.network_variants.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:id/network-variants',
    tokens: [{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/network-variants","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"network-variants","end":""}],
    types: placeholder as Registry['network-variants.read.network_variants.index']['types'],
  },
  'network-variants.read.network_variants.effective': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:id/network-variants/:network/effective',
    tokens: [{"old":"/api/v1/publications/:id/network-variants/:network/effective","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/network-variants/:network/effective","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/network-variants/:network/effective","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/network-variants/:network/effective","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/network-variants/:network/effective","type":0,"val":"network-variants","end":""},{"old":"/api/v1/publications/:id/network-variants/:network/effective","type":1,"val":"network","end":""},{"old":"/api/v1/publications/:id/network-variants/:network/effective","type":0,"val":"effective","end":""}],
    types: placeholder as Registry['network-variants.read.network_variants.effective']['types'],
  },
  'translations.read': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:id/translations',
    tokens: [{"old":"/api/v1/publications/:id/translations","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/translations","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/translations","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/translations","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/translations","type":0,"val":"translations","end":""}],
    types: placeholder as Registry['translations.read']['types'],
  },
  'translations.manage.translations.generate': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/translations/generate',
    tokens: [{"old":"/api/v1/publications/:id/translations/generate","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/translations/generate","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/translations/generate","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/translations/generate","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/translations/generate","type":0,"val":"translations","end":""},{"old":"/api/v1/publications/:id/translations/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['translations.manage.translations.generate']['types'],
  },
  'translations.manage.translations.update': {
    methods: ["PUT"],
    pattern: '/api/v1/publications/:id/translations/:locale',
    tokens: [{"old":"/api/v1/publications/:id/translations/:locale","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/translations/:locale","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/translations/:locale","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/translations/:locale","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/translations/:locale","type":0,"val":"translations","end":""},{"old":"/api/v1/publications/:id/translations/:locale","type":1,"val":"locale","end":""}],
    types: placeholder as Registry['translations.manage.translations.update']['types'],
  },
  'translations.manage.translations.approve': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/translations/:locale/approve',
    tokens: [{"old":"/api/v1/publications/:id/translations/:locale/approve","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/translations/:locale/approve","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/translations/:locale/approve","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/translations/:locale/approve","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/translations/:locale/approve","type":0,"val":"translations","end":""},{"old":"/api/v1/publications/:id/translations/:locale/approve","type":1,"val":"locale","end":""},{"old":"/api/v1/publications/:id/translations/:locale/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['translations.manage.translations.approve']['types'],
  },
  'network-variants.approve': {
    methods: ["POST"],
    pattern: '/api/v1/network-variants/:id/approve',
    tokens: [{"old":"/api/v1/network-variants/:id/approve","type":0,"val":"api","end":""},{"old":"/api/v1/network-variants/:id/approve","type":0,"val":"v1","end":""},{"old":"/api/v1/network-variants/:id/approve","type":0,"val":"network-variants","end":""},{"old":"/api/v1/network-variants/:id/approve","type":1,"val":"id","end":""},{"old":"/api/v1/network-variants/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['network-variants.approve']['types'],
  },
  'network-variants.manage.network_variants.store': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/network-variants',
    tokens: [{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/network-variants","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/network-variants","type":0,"val":"network-variants","end":""}],
    types: placeholder as Registry['network-variants.manage.network_variants.store']['types'],
  },
  'network-variants.manage.network_variants.generate': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/network-variants/generate',
    tokens: [{"old":"/api/v1/publications/:id/network-variants/generate","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/network-variants/generate","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/network-variants/generate","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/network-variants/generate","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/network-variants/generate","type":0,"val":"network-variants","end":""},{"old":"/api/v1/publications/:id/network-variants/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['network-variants.manage.network_variants.generate']['types'],
  },
  'network-variants.manage.network_variants.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/network-variants/:id',
    tokens: [{"old":"/api/v1/network-variants/:id","type":0,"val":"api","end":""},{"old":"/api/v1/network-variants/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/network-variants/:id","type":0,"val":"network-variants","end":""},{"old":"/api/v1/network-variants/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['network-variants.manage.network_variants.update']['types'],
  },
  'network-variants.manage.network_variants.stale': {
    methods: ["POST"],
    pattern: '/api/v1/network-variants/:id/stale',
    tokens: [{"old":"/api/v1/network-variants/:id/stale","type":0,"val":"api","end":""},{"old":"/api/v1/network-variants/:id/stale","type":0,"val":"v1","end":""},{"old":"/api/v1/network-variants/:id/stale","type":0,"val":"network-variants","end":""},{"old":"/api/v1/network-variants/:id/stale","type":1,"val":"id","end":""},{"old":"/api/v1/network-variants/:id/stale","type":0,"val":"stale","end":""}],
    types: placeholder as Registry['network-variants.manage.network_variants.stale']['types'],
  },
  'projects.projects.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/projects',
    tokens: [{"old":"/api/v1/projects","type":0,"val":"api","end":""},{"old":"/api/v1/projects","type":0,"val":"v1","end":""},{"old":"/api/v1/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['projects.projects.index']['types'],
  },
  'projects.projects.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/projects/:id',
    tokens: [{"old":"/api/v1/projects/:id","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['projects.projects.show']['types'],
  },
  'projects.manage.projects.store': {
    methods: ["POST"],
    pattern: '/api/v1/projects',
    tokens: [{"old":"/api/v1/projects","type":0,"val":"api","end":""},{"old":"/api/v1/projects","type":0,"val":"v1","end":""},{"old":"/api/v1/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['projects.manage.projects.store']['types'],
  },
  'projects.manage.projects.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/projects/:id',
    tokens: [{"old":"/api/v1/projects/:id","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['projects.manage.projects.update']['types'],
  },
  'projects.manage.projects.archive': {
    methods: ["DELETE"],
    pattern: '/api/v1/projects/:id',
    tokens: [{"old":"/api/v1/projects/:id","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['projects.manage.projects.archive']['types'],
  },
  'projects.manage.projects.restore': {
    methods: ["POST"],
    pattern: '/api/v1/projects/:id/restore',
    tokens: [{"old":"/api/v1/projects/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:id/restore","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/projects/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['projects.manage.projects.restore']['types'],
  },
  'calendar.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/calendar',
    tokens: [{"old":"/api/v1/calendar","type":0,"val":"api","end":""},{"old":"/api/v1/calendar","type":0,"val":"v1","end":""},{"old":"/api/v1/calendar","type":0,"val":"calendar","end":""}],
    types: placeholder as Registry['calendar.index']['types'],
  },
  'publications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/projects/:projectId/publications',
    tokens: [{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:projectId/publications","type":1,"val":"projectId","end":""},{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"publications","end":""}],
    types: placeholder as Registry['publications.index']['types'],
  },
  'publications.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:id',
    tokens: [{"old":"/api/v1/publications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['publications.show']['types'],
  },
  'discussion.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:id/discussion',
    tokens: [{"old":"/api/v1/publications/:id/discussion","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/discussion","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/discussion","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/discussion","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/discussion","type":0,"val":"discussion","end":""}],
    types: placeholder as Registry['discussion.show']['types'],
  },
  'media.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:id/media',
    tokens: [{"old":"/api/v1/publications/:id/media","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/media","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/media","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/media","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['media.index']['types'],
  },
  'media.read_url': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/media/:id/read-url',
    tokens: [{"old":"/api/v1/media/:id/read-url","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id/read-url","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id/read-url","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id/read-url","type":1,"val":"id","end":""},{"old":"/api/v1/media/:id/read-url","type":0,"val":"read-url","end":""}],
    types: placeholder as Registry['media.read_url']['types'],
  },
  'annotations.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/publications/:publicationId/media/:mediaId/annotations',
    tokens: [{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":1,"val":"publicationId","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"media","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":1,"val":"mediaId","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"annotations","end":""}],
    types: placeholder as Registry['annotations.index']['types'],
  },
  'comments.store': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/comments',
    tokens: [{"old":"/api/v1/publications/:id/comments","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/comments","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/comments","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/comments","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['comments.store']['types'],
  },
  'comments.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/comments/:id',
    tokens: [{"old":"/api/v1/comments/:id","type":0,"val":"api","end":""},{"old":"/api/v1/comments/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/comments/:id","type":0,"val":"comments","end":""},{"old":"/api/v1/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['comments.update']['types'],
  },
  'comments.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/comments/:id',
    tokens: [{"old":"/api/v1/comments/:id","type":0,"val":"api","end":""},{"old":"/api/v1/comments/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/comments/:id","type":0,"val":"comments","end":""},{"old":"/api/v1/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['comments.destroy']['types'],
  },
  'reviews.store': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/reviews',
    tokens: [{"old":"/api/v1/publications/:id/reviews","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/reviews","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/reviews","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/reviews","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/reviews","type":0,"val":"reviews","end":""}],
    types: placeholder as Registry['reviews.store']['types'],
  },
  'annotations.store': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:publicationId/media/:mediaId/annotations',
    tokens: [{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":1,"val":"publicationId","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"media","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":1,"val":"mediaId","end":""},{"old":"/api/v1/publications/:publicationId/media/:mediaId/annotations","type":0,"val":"annotations","end":""}],
    types: placeholder as Registry['annotations.store']['types'],
  },
  'annotations.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/annotations/:id',
    tokens: [{"old":"/api/v1/annotations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/annotations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/annotations/:id","type":0,"val":"annotations","end":""},{"old":"/api/v1/annotations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annotations.update']['types'],
  },
  'annotations.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/annotations/:id',
    tokens: [{"old":"/api/v1/annotations/:id","type":0,"val":"api","end":""},{"old":"/api/v1/annotations/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/annotations/:id","type":0,"val":"annotations","end":""},{"old":"/api/v1/annotations/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annotations.destroy']['types'],
  },
  'notifications.notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/notifications',
    tokens: [{"old":"/api/v1/notifications","type":0,"val":"api","end":""},{"old":"/api/v1/notifications","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.notifications.index']['types'],
  },
  'notifications.notifications.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/notifications/:id',
    tokens: [{"old":"/api/v1/notifications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/notifications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications/:id","type":0,"val":"notifications","end":""},{"old":"/api/v1/notifications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['notifications.notifications.update']['types'],
  },
  'publications.store': {
    methods: ["POST"],
    pattern: '/api/v1/projects/:projectId/publications',
    tokens: [{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"api","end":""},{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"v1","end":""},{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"projects","end":""},{"old":"/api/v1/projects/:projectId/publications","type":1,"val":"projectId","end":""},{"old":"/api/v1/projects/:projectId/publications","type":0,"val":"publications","end":""}],
    types: placeholder as Registry['publications.store']['types'],
  },
  'publications.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/publications/:id',
    tokens: [{"old":"/api/v1/publications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['publications.update']['types'],
  },
  'publications.duplicate': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/duplicate',
    tokens: [{"old":"/api/v1/publications/:id/duplicate","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/duplicate","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/duplicate","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/duplicate","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['publications.duplicate']['types'],
  },
  'publications.archive': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/archive',
    tokens: [{"old":"/api/v1/publications/:id/archive","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/archive","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/archive","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/archive","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/archive","type":0,"val":"archive","end":""}],
    types: placeholder as Registry['publications.archive']['types'],
  },
  'publications.transition': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/transition',
    tokens: [{"old":"/api/v1/publications/:id/transition","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/transition","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/transition","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/transition","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/transition","type":0,"val":"transition","end":""}],
    types: placeholder as Registry['publications.transition']['types'],
  },
  'calendar.move': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/calendar/move',
    tokens: [{"old":"/api/v1/publications/:id/calendar/move","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/calendar/move","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/calendar/move","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/calendar/move","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/calendar/move","type":0,"val":"calendar","end":""},{"old":"/api/v1/publications/:id/calendar/move","type":0,"val":"move","end":""}],
    types: placeholder as Registry['calendar.move']['types'],
  },
  'media.initialize': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/media/uploads',
    tokens: [{"old":"/api/v1/publications/:id/media/uploads","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/media/uploads","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/media/uploads","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/media/uploads","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/media/uploads","type":0,"val":"media","end":""},{"old":"/api/v1/publications/:id/media/uploads","type":0,"val":"uploads","end":""}],
    types: placeholder as Registry['media.initialize']['types'],
  },
  'media.finalize': {
    methods: ["POST"],
    pattern: '/api/v1/media/:id/finalize',
    tokens: [{"old":"/api/v1/media/:id/finalize","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id/finalize","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id/finalize","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id/finalize","type":1,"val":"id","end":""},{"old":"/api/v1/media/:id/finalize","type":0,"val":"finalize","end":""}],
    types: placeholder as Registry['media.finalize']['types'],
  },
  'media.attach': {
    methods: ["POST"],
    pattern: '/api/v1/publications/:id/media',
    tokens: [{"old":"/api/v1/publications/:id/media","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/media","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/media","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/media","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['media.attach']['types'],
  },
  'media.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/media/:id',
    tokens: [{"old":"/api/v1/media/:id","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media.update']['types'],
  },
  'media.reorder': {
    methods: ["PATCH"],
    pattern: '/api/v1/publications/:id/media/order',
    tokens: [{"old":"/api/v1/publications/:id/media/order","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/media/order","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/media/order","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/media/order","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/media/order","type":0,"val":"media","end":""},{"old":"/api/v1/publications/:id/media/order","type":0,"val":"order","end":""}],
    types: placeholder as Registry['media.reorder']['types'],
  },
  'media.detach': {
    methods: ["DELETE"],
    pattern: '/api/v1/publications/:id/media/:mediaId',
    tokens: [{"old":"/api/v1/publications/:id/media/:mediaId","type":0,"val":"api","end":""},{"old":"/api/v1/publications/:id/media/:mediaId","type":0,"val":"v1","end":""},{"old":"/api/v1/publications/:id/media/:mediaId","type":0,"val":"publications","end":""},{"old":"/api/v1/publications/:id/media/:mediaId","type":1,"val":"id","end":""},{"old":"/api/v1/publications/:id/media/:mediaId","type":0,"val":"media","end":""},{"old":"/api/v1/publications/:id/media/:mediaId","type":1,"val":"mediaId","end":""}],
    types: placeholder as Registry['media.detach']['types'],
  },
  'media.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/media/:id',
    tokens: [{"old":"/api/v1/media/:id","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media.destroy']['types'],
  },
  'media.purge': {
    methods: ["POST"],
    pattern: '/api/v1/media/:id/purge',
    tokens: [{"old":"/api/v1/media/:id/purge","type":0,"val":"api","end":""},{"old":"/api/v1/media/:id/purge","type":0,"val":"v1","end":""},{"old":"/api/v1/media/:id/purge","type":0,"val":"media","end":""},{"old":"/api/v1/media/:id/purge","type":1,"val":"id","end":""},{"old":"/api/v1/media/:id/purge","type":0,"val":"purge","end":""}],
    types: placeholder as Registry['media.purge']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
