/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/facebook.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/instagram.ts" />
/// <reference path="../../config/limiter.ts" />
/// <reference path="../../config/linkedin.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/media.ts" />
/// <reference path="../../config/pinterest.ts" />
/// <reference path="../../config/redis.ts" />
/// <reference path="../../config/tiktok.ts" />
