/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiGenerationSchema extends BaseModel {
  static $columns = ['agencyId', 'appliedAt', 'appliedVariantId', 'cancelledAt', 'completedAt', 'createdAt', 'createdBy', 'errorCode', 'id', 'inputHash', 'model', 'outputJson', 'promptVersion', 'provider', 'publicationId', 'status', 'usageJson'] as const
  $columns = AiGenerationSchema.$columns
  @column()
  declare agencyId: string
  @column.dateTime()
  declare appliedAt: DateTime | null
  @column()
  declare appliedVariantId: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare errorCode: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inputHash: string
  @column()
  declare model: string
  @column()
  declare outputJson: any
  @column()
  declare promptVersion: string
  @column()
  declare provider: string
  @column()
  declare publicationId: string
  @column()
  declare status: string
  @column()
  declare usageJson: any
}

export class AnnotationSchema extends BaseModel {
  static $columns = ['authorId', 'body', 'commentId', 'createdAt', 'deletedAt', 'height', 'id', 'mediaId', 'publicationId', 'publicationVersion', 'shape', 'updatedAt', 'width', 'x', 'y'] as const
  $columns = AnnotationSchema.$columns
  @column()
  declare authorId: string
  @column()
  declare body: string
  @column()
  declare commentId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mediaId: string
  @column()
  declare publicationId: string
  @column()
  declare publicationVersion: number
  @column()
  declare shape: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare width: number | null
  @column()
  declare x: number
  @column()
  declare y: number
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'createdAt', 'entityId', 'entityType', 'id', 'metadataJson', 'nextValues', 'previousValues', 'targetMediaId', 'targetProjectId', 'targetPublicationId', 'targetUserId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string | null
  @column()
  declare entityType: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadataJson: any
  @column()
  declare nextValues: any
  @column()
  declare previousValues: any
  @column()
  declare targetMediaId: string | null
  @column()
  declare targetProjectId: string | null
  @column()
  declare targetPublicationId: string | null
  @column()
  declare targetUserId: string | null
}

export class BackupRunSchema extends BaseModel {
  static $columns = ['checksum', 'completedAt', 'errorRedacted', 'id', 'objectKey', 'restoredAt', 'retentionTier', 'sizeBytes', 'startedAt', 'status', 'type', 'verifiedAt'] as const
  $columns = BackupRunSchema.$columns
  @column()
  declare checksum: string | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare errorRedacted: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare objectKey: string | null
  @column.dateTime()
  declare restoredAt: DateTime | null
  @column()
  declare retentionTier: string | null
  @column()
  declare sizeBytes: bigint | number | null
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class CalendarFeedTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastUsedAt', 'projectId', 'revokedAt', 'tokenHash', 'userId'] as const
  $columns = CalendarFeedTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare projectId: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare tokenHash: string
  @column()
  declare userId: string
}

export class CommentSchema extends BaseModel {
  static $columns = ['authorId', 'body', 'createdAt', 'deletedAt', 'editedAt', 'id', 'publicationId'] as const
  $columns = CommentSchema.$columns
  @column()
  declare authorId: string
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime()
  declare editedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare publicationId: string
}

export class MediaAssetSchema extends BaseModel {
  static $columns = ['agencyId', 'altText', 'checksum', 'createdAt', 'deletedAt', 'durationMs', 'height', 'id', 'isDecorative', 'mimeType', 'originalName', 'scanStatus', 'sizeBytes', 'storageKey', 'uploadExpiresAt', 'uploaderId', 'width'] as const
  $columns = MediaAssetSchema.$columns
  @column()
  declare agencyId: string
  @column()
  declare altText: string | null
  @column()
  declare checksum: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare durationMs: bigint | number | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDecorative: boolean
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare scanStatus: string
  @column()
  declare sizeBytes: bigint | number
  @column()
  declare storageKey: string
  @column.dateTime()
  declare uploadExpiresAt: DateTime
  @column()
  declare uploaderId: string
  @column()
  declare width: number | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'emailAttempts', 'emailJobId', 'emailLastError', 'emailStatus', 'emailedAt', 'id', 'payloadJson', 'readAt', 'type', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailAttempts: number
  @column()
  declare emailJobId: string | null
  @column()
  declare emailLastError: string | null
  @column()
  declare emailStatus: string
  @column.dateTime()
  declare emailedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare payloadJson: any
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare type: string
  @column()
  declare userId: string
}

export class ProjectMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'membershipRole', 'projectId', 'userId'] as const
  $columns = ProjectMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare membershipRole: string
  @column({ isPrimary: true })
  declare projectId: string
  @column()
  declare userId: string
}

export class ProjectSchema extends BaseModel {
  static $columns = ['agencyId', 'archivedAt', 'clientUserId', 'createdAt', 'createdBy', 'description', 'id', 'name', 'status', 'timezone', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column()
  declare agencyId: string
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare clientUserId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PublicationAttemptSchema extends BaseModel {
  static $columns = ['attempt', 'finishedAt', 'id', 'normalizedError', 'remotePostId', 'result', 'scheduledId', 'startedAt'] as const
  $columns = PublicationAttemptSchema.$columns
  @column()
  declare attempt: number
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare normalizedError: any | null
  @column()
  declare remotePostId: string | null
  @column()
  declare result: string
  @column()
  declare scheduledId: string
  @column.dateTime()
  declare startedAt: DateTime
}

export class PublicationMediaSchema extends BaseModel {
  static $columns = ['createdAt', 'mediaId', 'position', 'publicationId'] as const
  $columns = PublicationMediaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare mediaId: string
  @column()
  declare position: number
  @column({ isPrimary: true })
  declare publicationId: string
}

export class PublicationNetworkVariantSchema extends BaseModel {
  static $columns = ['approvedAt', 'approvedBy', 'createdAt', 'createdBy', 'generatedByAi', 'id', 'network', 'publicationId', 'sourceVersion', 'staleAt', 'status', 'text', 'updatedAt'] as const
  $columns = PublicationNetworkVariantSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare generatedByAi: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare network: string
  @column()
  declare publicationId: string
  @column()
  declare sourceVersion: number
  @column.dateTime()
  declare staleAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare text: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PublicationReviewSchema extends BaseModel {
  static $columns = ['createdAt', 'decision', 'id', 'message', 'publicationId', 'reviewerId', 'version'] as const
  $columns = PublicationReviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare decision: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string | null
  @column()
  declare publicationId: string
  @column()
  declare reviewerId: string
  @column()
  declare version: number
}

export class PublicationTranslationSchema extends BaseModel {
  static $columns = ['agencyId', 'approvedAt', 'approvedBy', 'createdAt', 'createdBy', 'generatedByAi', 'id', 'model', 'provider', 'publicationId', 'sourceHash', 'sourceLocale', 'sourceVersion', 'status', 'targetLocale', 'text', 'updatedAt'] as const
  $columns = PublicationTranslationSchema.$columns
  @column()
  declare agencyId: string
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare generatedByAi: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare model: string | null
  @column()
  declare provider: string | null
  @column()
  declare publicationId: string
  @column()
  declare sourceHash: string
  @column()
  declare sourceLocale: string
  @column()
  declare sourceVersion: number
  @column()
  declare status: string
  @column()
  declare targetLocale: string
  @column()
  declare text: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PublicationVersionSchema extends BaseModel {
  static $columns = ['authorId', 'createdAt', 'publicationId', 'snapshotJson', 'version'] as const
  $columns = PublicationVersionSchema.$columns
  @column()
  declare authorId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare publicationId: string
  @column()
  declare snapshotJson: any
  @column()
  declare version: number
}

export class PublicationSchema extends BaseModel {
  static $columns = ['agencyId', 'approvedVersion', 'archivedAt', 'baseText', 'contentVersion', 'createdAt', 'createdBy', 'id', 'projectId', 'scheduledAt', 'status', 'targetNetworks', 'timezone', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = PublicationSchema.$columns
  @column()
  declare agencyId: string
  @column()
  declare approvedVersion: number | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare baseText: string
  @column()
  declare contentVersion: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare projectId: string
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare targetNetworks: any
  @column()
  declare timezone: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string
}

export class ScheduledPublicationSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'id', 'idempotencyKey', 'network', 'networkPayloadJson', 'payloadHash', 'providerJobId', 'providerStatus', 'publicationId', 'publicationVersion', 'runAt', 'status', 'updatedAt'] as const
  $columns = ScheduledPublicationSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idempotencyKey: string
  @column()
  declare network: string
  @column()
  declare networkPayloadJson: any
  @column()
  declare payloadHash: string
  @column()
  declare providerJobId: string | null
  @column()
  declare providerStatus: string | null
  @column()
  declare publicationId: string
  @column()
  declare publicationVersion: number
  @column.dateTime()
  declare runAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SocialAccountSchema extends BaseModel {
  static $columns = ['agencyId', 'createdAt', 'createdBy', 'encryptedAccessToken', 'encryptedRefreshToken', 'expiresAt', 'externalAccountId', 'externalAccountName', 'id', 'metadataJson', 'network', 'revokedAt', 'scopes', 'status', 'updatedAt'] as const
  $columns = SocialAccountSchema.$columns
  @column()
  declare agencyId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare encryptedAccessToken: string | null
  @column()
  declare encryptedRefreshToken: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare externalAccountId: string
  @column()
  declare externalAccountName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadataJson: any
  @column()
  declare network: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare scopes: any
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['agencyId', 'createdAt', 'displayName', 'email', 'id', 'isActive', 'locale', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare agencyId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare locale: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
